### ISSUE TITLE
Ukendt fil?

### ISSUE THREAD

**Issue by TunaWithSalmon** [TunaWithSalmon/Tower-Defense#10]
Hvad bruger vi denne fil til?

Tower-Defense/resources/images/Thumbs.db

**Comment by Jevri** [comment]
ved det ikke kan man se hvem der har tilføjet den? Jeg ville tro det nok er noget fra tilemap'et

**Comment by TunaWithSalmon** [comment]
Hvis den bruges til tilemap'et, så fjerner vi den, dog vil jeg gerne lige høre fra @Chillexer  eller @LasseHansen94 da de lavede tilemap'et.

**Comment by Chillexer** [comment]
Ja tror det har noget med tilemap'et at gøre men den virker ikke til at gøre andet end at forsvinde fra mappen efter noget tid som om det er en temp fil men som er blevet uploadet fordi programmet vi lavede mappet i nok stadig var åbent.

**Comment by TunaWithSalmon** [comment]
Har nu fjernet Thumbs.db fra seneste fra armyTower branch.
