### ISSUE TITLE
Nyt tower

### ISSUE THREAD

**Issue by TunaWithSalmon** [TunaWithSalmon/Tower-Defense#11]
Nyt tårn som skal kunne skyde to skud ad gangen.

**Comment by Jevri** [comment]
skulle gerne være blevet lavet i branch army tower

**Comment by TunaWithSalmon** [comment]
Godt tænkt har været inde og gøre så armyTower arver fra baseTower så kun "shoot" functionen skulle laves om.

**Comment by TunaWithSalmon** [comment]
armyTower er nu færdig og merged.
