### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by TunaWithSalmon** [TunaWithSalmon/Tower-Defense#14]
Et map skal laves og til det map skal der laves waypoints i JSON format. Mappet skal loades i koden og indlæse waypints.

@Chillexer @LasseHansen94 Kan i lave et texture til mappet og ligge det som png.

**Comment by Chillexer** [comment]
Kigger på det imorgen 👍

**Comment by TunaWithSalmon** [comment]
Mappet er blevet tilføjet med waypoints lavet i en javascript fil.
